/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@StyleSheet
@Template(FormPage.class)
public class WaterworksCashReceiptInitialPage extends javax.swing.JPanel {

    /**
     * Creates new form WaterworksCashReceiptInitialPage
     */
    public WaterworksCashReceiptInitialPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        xTextField1 = new com.rameses.rcp.control.XTextField();

        xRadio1.setName("txntype"); // NOI18N
        xRadio1.setOptionValue("billing");
        xRadio1.setShowCaption(false);
        xRadio1.setText("Regular Billing");
        xFormPanel1.add(xRadio1);

        xTextField3.setCaption("Acct No / Billing No");
        xTextField3.setDepends(new String[] {"txntype"});
        xTextField3.setName("txnid"); // NOI18N
        xTextField3.setVisibleWhen("#{ txntype == 'billing' }");
        xTextField3.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField3.setCaptionWidth(160);
        xTextField3.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 30));
        xTextField3.setRequired(true);
        xFormPanel1.add(xTextField3);

        xRadio2.setName("txntype"); // NOI18N
        xRadio2.setOptionValue("deposit");
        xRadio2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xRadio2.setShowCaption(false);
        xRadio2.setText("Deposit");
        xFormPanel1.add(xRadio2);

        xTextField2.setCaption("Acct No");
        xTextField2.setDepends(new String[] {"txntype"});
        xTextField2.setName("txnid"); // NOI18N
        xTextField2.setVisibleWhen("#{ txntype == 'deposit' }");
        xTextField2.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField2.setCaptionWidth(160);
        xTextField2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 30));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xDecimalField1.setCaption("Amount to Deposit");
        xDecimalField1.setDepends(new String[] {"txntype"});
        xDecimalField1.setName("depositAmt"); // NOI18N
        xDecimalField1.setVisibleWhen("#{ txntype == 'deposit' }");
        xDecimalField1.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xDecimalField1.setCaptionWidth(160);
        xDecimalField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xDecimalField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(160, 30));
        xDecimalField1.setRequired(true);
        xFormPanel1.add(xDecimalField1);

        xRadio3.setName("txntype"); // NOI18N
        xRadio3.setOptionValue("newapplication");
        xRadio3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xRadio3.setShowCaption(false);
        xRadio3.setText("New Application");
        xFormPanel1.add(xRadio3);

        xTextField1.setCaption("App No");
        xTextField1.setDepends(new String[] {"txntype"});
        xTextField1.setName("txnid"); // NOI18N
        xTextField1.setVisibleWhen("#{ txntype == 'newapplication' }");
        xTextField1.setCaptionFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField1.setCaptionWidth(120);
        xTextField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 30));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XRadio xRadio3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
}
