/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(OKCancelPage.class)
public class ConsumptionPostToLedgerPage extends javax.swing.JPanel {

    /**
     * Creates new form ConsumptionPostToLedgerPage
     */
    public ConsumptionPostToLedgerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xCheckBox2 = new com.rameses.rcp.control.XCheckBox();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xButton1 = new com.rameses.rcp.control.XButton();
        xCheckBox3 = new com.rameses.rcp.control.XCheckBox();

        xCheckBox2.setCaption("Post To Ledger");
        xCheckBox2.setCheckValue(1);
        xCheckBox2.setDepends(new String[] {"entity.reading", "entity.hold"});
        xCheckBox2.setName("entity.posttoledger"); // NOI18N
        xCheckBox2.setUncheckValue(0);
        xCheckBox2.setVisibleWhen("#{ entity.reading >0 && entity.hold == 0 }");
        xCheckBox2.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xCheckBox2.setShowCaption(false);
        xCheckBox2.setText("Post To Ledger");

        xFormPanel1.setDepends(new String[] {"entity.posttoledger", "entity.reading", "entity.hold"});
        xFormPanel1.setVisibleWhen("#{ entity.reading >0 && entity.hold == 0 && entity.posttoledger == 1 }");
        xFormPanel1.setShowCaption(false);

        xDecimalField2.setCaption("Amount");
        xDecimalField2.setName("entity.amount"); // NOI18N
        xDecimalField2.setCaptionWidth(100);
        xDecimalField2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xDecimalField2.setRequired(true);
        xDecimalField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xDecimalField2ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xDecimalField2);

        xDecimalField3.setCaption("Amt Paid");
        xDecimalField3.setName("entity.amtpaid"); // NOI18N
        xDecimalField3.setCaptionWidth(100);
        xDecimalField3.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xDecimalField3.setRequired(true);
        xDecimalField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xDecimalField3ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xDecimalField3);

        xDecimalField4.setCaption("Discount");
        xDecimalField4.setName("entity.discount"); // NOI18N
        xDecimalField4.setCaptionWidth(100);
        xDecimalField4.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xDecimalField4.setRequired(true);
        xDecimalField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xDecimalField4ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xDecimalField4);

        xButton1.setCaption("");
        xButton1.setName("recalc"); // NOI18N
        xButton1.setCaptionWidth(120);
        xButton1.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xButton1.setText("Calculate");
        xFormPanel1.add(xButton1);

        xCheckBox3.setCaption("Hold");
        xCheckBox3.setCheckValue(1);
        xCheckBox3.setDisableWhen("#{true}");
        xCheckBox3.setName("entity.system"); // NOI18N
        xCheckBox3.setUncheckValue(0);
        xCheckBox3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xCheckBox3.setShowCaption(false);
        xCheckBox3.setText("System Generated");
        xCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xCheckBox3ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xCheckBox3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xDecimalField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xDecimalField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xDecimalField2ActionPerformed

    private void xDecimalField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xDecimalField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xDecimalField3ActionPerformed

    private void xDecimalField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xDecimalField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xDecimalField4ActionPerformed

    private void xCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xCheckBox3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XCheckBox xCheckBox2;
    private com.rameses.rcp.control.XCheckBox xCheckBox3;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    // End of variables declaration//GEN-END:variables
}
