/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.WorkflowTaskFormPage;

/**
 *
 * @author elmonazareno
 */
@Template(WorkflowTaskFormPage.class)
public class WaterworksChangeRequestPage extends javax.swing.JPanel {

    /**
     * Creates new form WaterworksChangePage
     */
    public WaterworksChangeRequestPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        jPanel3 = new javax.swing.JPanel();
        pnlOwner = new com.rameses.rcp.control.XPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        xTextArea3 = new com.rameses.rcp.control.XTextArea();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLookupField2 = new com.rameses.rcp.control.XLookupField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        pnlLocation = new com.rameses.rcp.control.XPanel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();
        addressEditor1 = new com.rameses.enterprise.components.AddressEditor();
        pnlMeter = new com.rameses.rcp.control.XPanel();
        xFormPanel5 = new com.rameses.rcp.control.XFormPanel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xLabel19 = new com.rameses.rcp.control.XLabel();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        pnlAttributes = new com.rameses.rcp.control.XPanel();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();
        jScrollPane5 = new javax.swing.JScrollPane();
        xList2 = new com.rameses.rcp.control.XList();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton4 = new com.rameses.rcp.control.XButton();
        xButton5 = new com.rameses.rcp.control.XButton();
        pnlClassification = new com.rameses.rcp.control.XPanel();
        xFormPanel6 = new com.rameses.rcp.control.XFormPanel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        pnlContact = new com.rameses.rcp.control.XPanel();
        xFormPanel7 = new com.rameses.rcp.control.XFormPanel();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xTextField8 = new com.rameses.rcp.control.XTextField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        pnlSubarea = new com.rameses.rcp.control.XPanel();
        xFormPanel8 = new com.rameses.rcp.control.XFormPanel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLookupField4 = new com.rameses.rcp.control.XLookupField();
        xLookupField5 = new com.rameses.rcp.control.XLookupField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(461, 180));

        xFormPanel1.setName(""); // NOI18N
        xFormPanel1.setCaptionWidth(220);

        xTextField1.setCaption("Control No");
        xTextField1.setDisableWhen("#{ true }");
        xTextField1.setName("entity.controlno"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xTextField1);

        xLabel2.setCaption("App Type");
        xLabel2.setExpression("#{ entity.apptype }");
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        xLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xLabel2);

        xDateField1.setCaption("Date Filed");
        xDateField1.setDisableWhen("#{ mode != 'create' }");
        xDateField1.setName("entity.dtcreated"); // NOI18N
        xDateField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xFormPanel1.add(xDateField1);

        xLookupField1.setCaption("Account");
        xLookupField1.setDisableWhen("#{ mode != 'create' }");
        xLookupField1.setExpression("#{ entity.account.acctno }");
        xLookupField1.setHandler("vw_waterworks_account:lookup");
        xLookupField1.setName("entity.account"); // NOI18N
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField1);

        xLabel1.setCaption("Acct Name");
        xLabel1.setDepends(new String[] {"entity.account"});
        xLabel1.setExpression("#{ entity.account.acctname }");
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel1);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 50));

        xTextArea1.setCaption("Reason");
        xTextArea1.setName("entity.reason"); // NOI18N
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.CardLayout());

        pnlOwner.setVisibleWhen("#{ entity.apptype == 'CHANGE_OWNER' }");

        xFormPanel3.setCaptionWidth(220);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(0, 50));

        xTextArea3.setCaption("Current Owner");
        xTextArea3.setDepends(new String[] {"entity.account"});
        xTextArea3.setEditable(false);
        xTextArea3.setLineWrap(true);
        xTextArea3.setName("entity.account.owner.name"); // NOI18N
        xTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(xTextArea3);

        xFormPanel3.add(jScrollPane3);

        xLabel3.setCaption("No. of Units");
        xLabel3.setDepends(new String[] {"entity.account"});
        xLabel3.setExpression("#{ entity.account.units }");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel3);

        xLookupField2.setCaption("New Owner Name");
        xLookupField2.setExpression("#{entity.newaccount.owner.name}");
        xLookupField2.setHandler("entity:lookup");
        xLookupField2.setName("entity.newaccount.owner"); // NOI18N
        xLookupField2.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLookupField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLookupField2);

        xTextField2.setCaption("New Account Name");
        xTextField2.setDepends(new String[] {"entity.newaccount.owner"});
        xTextField2.setName("entity.newaccount.acctname"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        xFormPanel3.add(xTextField2);

        xIntegerField1.setCaption("No.of Units");
        xIntegerField1.setDepends(new String[] {"entity.account"});
        xIntegerField1.setName("entity.newaccount.units"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel3.add(xIntegerField1);

        javax.swing.GroupLayout pnlOwnerLayout = new javax.swing.GroupLayout(pnlOwner);
        pnlOwner.setLayout(pnlOwnerLayout);
        pnlOwnerLayout.setHorizontalGroup(
            pnlOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOwnerLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        pnlOwnerLayout.setVerticalGroup(
            pnlOwnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOwnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.add(pnlOwner, "card3");

        pnlLocation.setVisibleWhen("#{ entity.apptype == 'CHANGE_ADDRESS' }");

        xFormPanel2.setCaptionWidth(220);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 50));

        xTextArea2.setCaption("Current Address");
        xTextArea2.setDepends(new String[] {"entity.account"});
        xTextArea2.setEditable(false);
        xTextArea2.setLineWrap(true);
        xTextArea2.setName("entity.account.address.text"); // NOI18N
        xTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(xTextArea2);

        xFormPanel2.add(jScrollPane2);

        addressEditor1.setCaption("Account Address");
        addressEditor1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        addressEditor1.setDepends(new String[] {"entity.account"});
        addressEditor1.setName("entity.newaccount.address"); // NOI18N
        addressEditor1.setPreferredSize(new java.awt.Dimension(0, 53));
        addressEditor1.setRequired(true);
        xFormPanel2.add(addressEditor1);

        javax.swing.GroupLayout pnlLocationLayout = new javax.swing.GroupLayout(pnlLocation);
        pnlLocation.setLayout(pnlLocationLayout);
        pnlLocationLayout.setHorizontalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnlLocationLayout.setVerticalGroup(
            pnlLocationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.add(pnlLocation, "card5");

        pnlMeter.setVisibleWhen("#{ entity.apptype == 'CHANGE_METER' }");

        xFormPanel5.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel5.setCaptionWidth(220);
        xFormPanel5.setPadding(new java.awt.Insets(0, 5, 0, 5));

        xLabel5.setCaption("Current Meter Serial No/Brand");
        xLabel5.setDepends(new String[] {"entity.account"});
        xLabel5.setExpression("#{ entity.account.meter.serialno } #{ entity.account.meter.brand }");
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLabel5);

        xLabel6.setCaption("Current Meter Size/ Capacity");
        xLabel6.setDepends(new String[] {"entity.account"});
        xLabel6.setExpression("#{ entity.account.meter.size } #{ entity.account.meter.capacity }");
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLabel6);

        xLabel7.setCaption("Current Meter State");
        xLabel7.setDepends(new String[] {"entity.account"});
        xLabel7.setExpression("#{ entity.account.meterstate }");
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLabel7);

        xLabel10.setCaption("Current Meter Reading");
        xLabel10.setDepends(new String[] {"entity.account"});
        xLabel10.setExpression("#{ entity.account.meter.reading }");
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLabel10);

        xLookupField3.setCaption("New Meter Serial No/Brand");
        xLookupField3.setDepends(new String[] {});
        xLookupField3.setExpression("#{ entity.newaccount.meter.serialno } #{ entity.newaccount.meter.brand }");
        xLookupField3.setHandler("waterworks_meter_wo_account:lookup");
        xLookupField3.setName("entity.newaccount.meter"); // NOI18N
        xLookupField3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLookupField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLookupField3);

        xLabel19.setCaption("New Meter Size / Capacity");
        xLabel19.setDepends(new String[] {"entity.newaccount.meter"});
        xLabel19.setExpression("#{entity.newaccount.meter?.size} / #{entity.newaccount.meter.capacity}");
        xLabel19.setVisibleWhen("#{ entity.newaccount.meterid != null }");
        xLabel19.setBackground(new java.awt.Color(245, 245, 245));
        xLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        xLabel19.setOpaque(true);
        xLabel19.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel5.add(xLabel19);

        xComboBox2.setCaption("New Meter State");
        xComboBox2.setDepends(new String[] {"entity.newaccount.meter"});
        xComboBox2.setExpression("");
        xComboBox2.setItems("meterStates");
        xComboBox2.setName("entity.newaccount.meterstate"); // NOI18N
        xComboBox2.setVisibleWhen("#{ entity.newaccount.meterid != null }");
        xComboBox2.setRequired(true);
        xFormPanel5.add(xComboBox2);

        javax.swing.GroupLayout pnlMeterLayout = new javax.swing.GroupLayout(pnlMeter);
        pnlMeter.setLayout(pnlMeterLayout);
        pnlMeterLayout.setHorizontalGroup(
            pnlMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(xFormPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlMeterLayout.setVerticalGroup(
            pnlMeterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        jPanel3.add(pnlMeter, "card4");

        pnlAttributes.setVisibleWhen("#{ entity.apptype == 'CHANGE_ATTRIBUTES' }");

        xFormPanel4.setCaptionWidth(220);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(0, 90));

        xList1.setCaption("Current Attributes");
        xList1.setDepends(new String[] {"entity.account"});
        xList1.setItems("entity.account.attributes");
        xList1.setDynamic(true);
        xList1.setPreferredSize(new java.awt.Dimension(80, 30));
        jScrollPane4.setViewportView(xList1);

        xFormPanel4.add(jScrollPane4);

        jScrollPane5.setPreferredSize(new java.awt.Dimension(0, 90));

        xList2.setCaption("New Attributes");
        xList2.setDepends(new String[] {"entity.account"});
        xList2.setItems("entity.newaccount.attributes");
        xList2.setName("selectedAttribute"); // NOI18N
        xList2.setDynamic(true);
        xList2.setPreferredSize(new java.awt.Dimension(80, 30));
        jScrollPane5.setViewportView(xList2);

        xFormPanel4.add(jScrollPane5);

        xPanel1.setCaption("");
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        xButton4.setName("addAttribute"); // NOI18N
        xButton4.setVisibleWhen("#{ mode != 'read' }");
        xButton4.setImmediate(true);
        xButton4.setText("Add");
        xPanel1.add(xButton4);

        xButton5.setName("removeAttribute"); // NOI18N
        xButton5.setVisibleWhen("#{ mode != 'read' }");
        xButton5.setImmediate(true);
        xButton5.setText("Remove");
        xPanel1.add(xButton5);

        xFormPanel4.add(xPanel1);

        javax.swing.GroupLayout pnlAttributesLayout = new javax.swing.GroupLayout(pnlAttributes);
        pnlAttributes.setLayout(pnlAttributesLayout);
        pnlAttributesLayout.setHorizontalGroup(
            pnlAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttributesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pnlAttributesLayout.setVerticalGroup(
            pnlAttributesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttributesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.add(pnlAttributes, "card5");

        pnlClassification.setVisibleWhen("#{ entity.apptype == 'CHANGE_CLASSIFICATION' }");

        xFormPanel6.setCaptionWidth(220);

        xLabel4.setCaption("Current Classification");
        xLabel4.setDepends(new String[] {"entity.account"});
        xLabel4.setExpression("#{ entity.account.classification.objid }");
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel6.add(xLabel4);

        xComboBox1.setCaption("New Classification");
        xComboBox1.setExpression("#{item.objid}");
        xComboBox1.setItems("classTypes");
        xComboBox1.setName("entity.newaccount.classification"); // NOI18N
        xComboBox1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xComboBox1.setPreferredSize(new java.awt.Dimension(0, 20));
        xComboBox1.setRequired(true);
        xFormPanel6.add(xComboBox1);

        javax.swing.GroupLayout pnlClassificationLayout = new javax.swing.GroupLayout(pnlClassification);
        pnlClassification.setLayout(pnlClassificationLayout);
        pnlClassificationLayout.setHorizontalGroup(
            pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassificationLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        pnlClassificationLayout.setVerticalGroup(
            pnlClassificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClassificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel3.add(pnlClassification, "card6");

        pnlContact.setVisibleWhen("#{ entity.apptype == 'CHANGE_CONTACT' }");

        xFormPanel7.setCaptionWidth(220);

        xTextField5.setCaption("Current Email");
        xTextField5.setDepends(new String[] {"entity.account"});
        xTextField5.setDisableWhen("#{ true }");
        xTextField5.setName("entity.account.email"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField5.setTextCase(com.rameses.rcp.constant.TextCase.NONE);
        xFormPanel7.add(xTextField5);

        xTextField4.setCaption("Current Mobile No");
        xTextField4.setDepends(new String[] {"entity.account"});
        xTextField4.setDisableWhen("#{ true }");
        xTextField4.setName("entity.account.mobileno"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel7.add(xTextField4);

        xTextField6.setCaption("Current Phone No");
        xTextField6.setDepends(new String[] {"entity.account"});
        xTextField6.setDisableWhen("#{ true }");
        xTextField6.setName("entity.account.phoneno"); // NOI18N
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel7.add(xTextField6);

        xTextField7.setCaption("New Email");
        xTextField7.setDepends(new String[] {"entity.account"});
        xTextField7.setName("entity.newaccount.email"); // NOI18N
        xTextField7.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField7.setTextCase(com.rameses.rcp.constant.TextCase.NONE);
        xFormPanel7.add(xTextField7);

        xTextField8.setCaption("New Mobile No");
        xTextField8.setDepends(new String[] {"entity.account"});
        xTextField8.setName("entity.newaccount.mobileno"); // NOI18N
        xTextField8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel7.add(xTextField8);

        xTextField9.setCaption("New Phone No");
        xTextField9.setDepends(new String[] {"entity.account"});
        xTextField9.setName("entity.newaccount.phoneno"); // NOI18N
        xTextField9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel7.add(xTextField9);

        javax.swing.GroupLayout pnlContactLayout = new javax.swing.GroupLayout(pnlContact);
        pnlContact.setLayout(pnlContactLayout);
        pnlContactLayout.setHorizontalGroup(
            pnlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        pnlContactLayout.setVerticalGroup(
            pnlContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContactLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(xFormPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jPanel3.add(pnlContact, "card7");

        pnlSubarea.setVisibleWhen("#{ entity.apptype == 'CHANGE_SUBAREA' }");

        xFormPanel8.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel8.setCaptionWidth(220);
        xFormPanel8.setPadding(new java.awt.Insets(0, 5, 0, 5));

        xLabel8.setCaption("Current Subarea");
        xLabel8.setDepends(new String[] {"entity.account"});
        xLabel8.setExpression("#{ entity.account.subarea.code } - #{ entity.account.subarea.area.code }");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel8.add(xLabel8);

        xLabel9.setCaption("Stubout");
        xLabel9.setDepends(new String[] {"entity.account"});
        xLabel9.setExpression("#{ entity.account.stubout.code }");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel8.add(xLabel9);

        xLookupField4.setCaption("Sub Area");
        xLookupField4.setExpression("#{ entity.newaccount.subarea.code } - #{entity.newaccount.subarea.description}");
        xLookupField4.setHandler("waterworks_subarea:lookup");
        xLookupField4.setName("entity.newaccount.subarea"); // NOI18N
        xLookupField4.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLookupField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField4.setRequired(true);
        xFormPanel8.add(xLookupField4);

        xLookupField5.setCaption("Stubout");
        xLookupField5.setDepends(new String[] {"entity.newaccount.subarea"});
        xLookupField5.setExpression("#{ entity.newaccount.stubout.code } ");
        xLookupField5.setHandler("lookupStubout");
        xLookupField5.setName("entity.newaccount.stubout"); // NOI18N
        xLookupField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel8.add(xLookupField5);

        javax.swing.GroupLayout pnlSubareaLayout = new javax.swing.GroupLayout(pnlSubarea);
        pnlSubarea.setLayout(pnlSubareaLayout);
        pnlSubareaLayout.setHorizontalGroup(
            pnlSubareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubareaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(xFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        pnlSubareaLayout.setVerticalGroup(
            pnlSubareaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubareaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jPanel3.add(pnlSubarea, "card8");

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.AddressEditor addressEditor1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private com.rameses.rcp.control.XPanel pnlAttributes;
    private com.rameses.rcp.control.XPanel pnlClassification;
    private com.rameses.rcp.control.XPanel pnlContact;
    private com.rameses.rcp.control.XPanel pnlLocation;
    private com.rameses.rcp.control.XPanel pnlMeter;
    private com.rameses.rcp.control.XPanel pnlOwner;
    private com.rameses.rcp.control.XPanel pnlSubarea;
    private com.rameses.rcp.control.XButton xButton4;
    private com.rameses.rcp.control.XButton xButton5;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XFormPanel xFormPanel5;
    private com.rameses.rcp.control.XFormPanel xFormPanel6;
    private com.rameses.rcp.control.XFormPanel xFormPanel7;
    private com.rameses.rcp.control.XFormPanel xFormPanel8;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel19;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XList xList1;
    private com.rameses.rcp.control.XList xList2;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XLookupField xLookupField2;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XLookupField xLookupField4;
    private com.rameses.rcp.control.XLookupField xLookupField5;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    private com.rameses.rcp.control.XTextArea xTextArea3;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField8;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
