/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class WaterworksApplicationEntryPage extends javax.swing.JPanel {

    /**
     * Creates new form WaterworksApplicationEntryPage
     */
    public WaterworksApplicationEntryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        xTextArea2 = new com.rameses.rcp.control.XTextArea();

        xFormPanel1.setCaptionWidth(150);
        xFormPanel1.setPadding(new java.awt.Insets(10, 5, 0, 5));

        xLabel1.setCaption("App Type");
        xLabel1.setExpression("#{ entity.apptype }");
        xLabel1.setName(""); // NOI18N
        xFormPanel1.add(xLabel1);

        xDateField1.setCaption("App Date");
        xDateField1.setName("entity.appdate"); // NOI18N
        xFormPanel1.add(xDateField1);

        xLabel2.setCaption("Applicant");
        xLabel2.setExpression("#{ entity.owner.name }");
        xLabel2.setName(""); // NOI18N
        xLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel2);

        xLabel3.setCaption("Acct Name");
        xLabel3.setExpression("#{ entity.acctname }");
        xLabel3.setName(""); // NOI18N
        xLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel3);

        xLabel4.setCaption("Location");
        xLabel4.setExpression("#{ entity.address.text }");
        xLabel4.setName(""); // NOI18N
        xLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 40));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Classification");
        xLabel5.setExpression("#{ entity.classificationid }");
        xLabel5.setName(""); // NOI18N
        xLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel5);

        xLabel6.setCaption("Meter");
        xLabel6.setExpression("Serial No: #{ entity.account.meter.serialno } #{ entity.account.meter.brand } #{ entity.account.meter.size.title }");
        xLabel6.setName(""); // NOI18N
        xLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel6.setVisibleWhen("#{ entity.account.meter?.objid != null }");
        xLabel6.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel6);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(0, 50));

        xTextArea2.setCaption("Remarks");
        xTextArea2.setName("entity.remarks"); // NOI18N
        xTextArea2.setWrapStyleWord(true);
        xTextArea2.setCellPadding(new java.awt.Insets(5, 0, 0, 0));
        xTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        xTextArea2.setMargin(new java.awt.Insets(5, 10, 1, 3));
        jScrollPane2.setViewportView(xTextArea2);

        xFormPanel1.add(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XTextArea xTextArea2;
    // End of variables declaration//GEN-END:variables
}
