/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.waterworks.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(OKCancelPage.class)
public class WaterworksApplicationApprovalPage extends javax.swing.JPanel {

    /**
     * Creates new form WaterworksNewConnectionApprovalPage
     */
    public WaterworksApplicationApprovalPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        monthList1 = new com.rameses.enterprise.components.MonthList();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField3 = new com.rameses.rcp.control.XIntegerField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(20, 20, 20, 20));
        xTitledBorder1.setTitle("Billing Info");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCellpadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel1.setPadding(new java.awt.Insets(0, 20, 5, 5));

        xLabel1.setExpression("Enter next bill year and month");
        xLabel1.setShowCaption(false);
        xFormPanel1.add(xLabel1);

        xIntegerField1.setCaption("Year");
        xIntegerField1.setName("year"); // NOI18N
        xIntegerField1.setCaptionWidth(120);
        xIntegerField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        monthList1.setCaption("Month");
        monthList1.setCaptionWidth(120);
        monthList1.setName("month"); // NOI18N
        monthList1.setRequired(true);
        xFormPanel1.add(monthList1);

        xFormPanel2.setCaption("Reading Seq No");
        com.rameses.rcp.control.border.XTitledBorder xTitledBorder2 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder2.setPadding(new java.awt.Insets(30, 20, 20, 20));
        xTitledBorder2.setTitle("Reading Seq No");
        xFormPanel2.setBorder(xTitledBorder2);
        xFormPanel2.setCellpadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel2.setPadding(new java.awt.Insets(0, 20, 5, 5));

        xIntegerField2.setCaption("Seq No");
        xIntegerField2.setName("seqno"); // NOI18N
        xIntegerField2.setCaptionWidth(120);
        xIntegerField2.setRequired(true);
        xFormPanel2.add(xIntegerField2);

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder3 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder3.setPadding(new java.awt.Insets(30, 20, 20, 20));
        xTitledBorder3.setTitle("Meter Initial Reading");
        xFormPanel3.setBorder(xTitledBorder3);
        xFormPanel3.setCellpadding(new java.awt.Insets(0, 20, 0, 0));
        xFormPanel3.setPadding(new java.awt.Insets(0, 20, 5, 5));

        xIntegerField3.setCaption("Initial Reading");
        xIntegerField3.setName("reading"); // NOI18N
        xIntegerField3.setCaptionWidth(120);
        xIntegerField3.setRequired(true);
        xFormPanel3.add(xIntegerField3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xFormPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.MonthList monthList1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField3;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
}
